# Generated by Django 3.2 on 2022-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('SELLER', 'seller'), ('SUPERADMIN', 'super admin'), ('CUSTOMER', 'customer')], max_length=11, null=True),
        ),
    ]
